version: '3'
services:
  redis:
    image: redis
    ports:
      - "8379:6379"
  mysql:
    image: "mysql"
    container_name: mysql
    restart: always
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ=Asia/Seoul
    volumes:
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci