version: '3'
services:
  redis:
    image: redis
    ports:
      - "8379:6379"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "4306:3306"