server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600
spring:
  application:
    name: Stoury
  kafka:
    topic-name: chats
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.stoury.dto.chat.ChatMessageResponse
  data:
    redis:
      port: 8379
      host: localhost
  batch:
    job:
      enabled: false
      names: jobPopularSpots,jobYearlyDiaries,jobDailyFeeds,jobMonthlyFeeds,jobWeeklyFeeds
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:4306/stourydev?allowPublicKeyRetrieval=true&useSSL=false&sendFractionalSeconds=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 50
      defer-datasource-initialization: false
    open-in-view: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
path-prefix: /feeds
profileImage:
  path-prefix: /members/profiles
google:
  geocoding:
    api-key: geocodeapikey
origin: https://temp.stoury.com
token:
  secret: tokensecret
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      instance_id: ${HOSTNAME}
      application: ${spring.application.name}