spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/stoury
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect