spring:
  jpa:
    show-sql: false
  data:
    redis:
      port: 6379
      host: ${redis.host}
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    url: jdbc:mariadb://${db.host}:3306/stouryprod?allowPublicKeyRetrieval=true&useSSL=false&sendFractionalSeconds=false
    username: ${db.username}
    password: ${db.password}
logging:
  level:
    org.hibernate.orm.jdbc.bind: off
google:
  geocoding:
    api-key: ${geocode.apikey:NONE}
origin: ${origin:NONE}
token:
  secret: ${token.secret:NONE}