server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600
spring:
  data:
    redis:
      port: 8379
      host: localhost
  batch:
    job:
      enabled: false
      names: updatePopularSpotsJob,updateHotFeedsJob
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:4306/stourydev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      defer-datasource-initialization: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
path-prefix: /feeds
profileImage:
  path-prefix: /members/profiles
google:
  geocoding:
    api-key: geocodeapikey
origin: https://temp.stoury.com
token:
  secret: tokensecret