spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:3306/stoury_test
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 8379
  session:
    redis:
      namespace: stoury:dev-session
      flush-mode: on_save
logging:
  level:
    org.springframework.security: trace
token-secret: "TOKEN_SECRET_DEV"
path-prefix: ${FEEDS}
profileImage:
  path-prefix: ${PROFILE_IMAGES}