spring:
  datasource:
    url: jdbc:mariadb://localhost:4306/testdb?allowPublicKeyRetrieval=true&useSSL=false&sendFractionalSeconds=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver