spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/stoury
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
path-prefix: /feeds
profileImage:
  path-prefix: /members/profiles