spring:
  data:
    redis:
      port: 8379
      host: localhost
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: updatePopularSpotsJob,updateHotFeedsJob
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

token-secret: TOKEN_SECRET_TEST