spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:4306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 8379
  session:
    redis:
      namespace: stoury:dev-session
      flush-mode: on_save
logging:
  level:
    org.springframework.security: trace
path-prefix: /graphiccontents
profileImage:
  path-prefix: /profileimages
google:
  geocoding:
    api-key: dummykey