spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace