ALTER TABLE `COMMENT`
 MODIFY `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `DIARY`
 MODIFY `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `FEED`
 MODIFY `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `CHAT_MESSAGE`
 MODIFY `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP;