ALTER TABLE FEED DROP INDEX INDEX_CREATED_AT;
ALTER TABLE FEED ADD INDEX INDEX_CREATED_AT (CREATED_AT DESC);

ALTER TABLE COMMENT DROP INDEX COMMENT_INDEX_CREATED_AT;
ALTER TABLE COMMENT ADD INDEX COMMENT_INDEX_CREATED_AT (CREATED_AT DESC);

ALTER TABLE DIARY DROP INDEX DIARY_INDEX_CREATED_AT;
ALTER TABLE DIARY ADD INDEX DIARY_INDEX_CREATED_AT (CREATED_AT DESC);

ALTER TABLE CHAT_MESSAGE DROP INDEX CHAT_MESSAGE_INDEX_CREATED_AT;
ALTER TABLE CHAT_MESSAGE ADD INDEX CHAT_MESSAGE_INDEX_CREATED_AT (CREATED_AT DESC);