-- 대댓글 테이블 생성
CREATE TABLE `CHILD_COMMENT`
(
    `ID`                BIGINT       NOT NULL AUTO_INCREMENT,
    `MEMBER_ID`         BIGINT       NOT NULL,
    `PARENT_COMMENT_ID` BIGINT,
    `TEXT_CONTENT`      VARCHAR(200) NOT NULL,
    `CREATED_AT`        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `DELETED`           TINYINT(1)      NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`),
    FOREIGN KEY (`PARENT_COMMENT_ID`) REFERENCES `COMMENT` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

-- 기존 댓글테이블에서 대댓글테이블로 마이그레이션
INSERT INTO CHILD_COMMENT( MEMBER_ID, PARENT_COMMENT_ID, TEXT_CONTENT, CREATED_AT, DELETED)
SELECT MEMBER_ID, PARENT_COMMENT_ID, TEXT_CONTENT, CREATED_AT, DELETED
FROM COMMENT
WHERE PARENT_COMMENT_ID IS NOT NULL;

-- 기존 댓글 테이블의 데이터 삭제
DELETE FROM COMMENT
WHERE PARENT_COMMENT_ID IS NOT NULL;

-- 기존 댓글 테이블의 외래키 제약조건 삭제
DELIMITER $$

CREATE PROCEDURE DropForeignKey()
BEGIN
    DECLARE fk_name CHAR(64);

    -- 외래키 제약 조건 이름 조회
    SELECT CONSTRAINT_NAME INTO fk_name
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    WHERE TABLE_NAME = 'COMMENT' AND COLUMN_NAME = 'PARENT_COMMENT_ID'
    LIMIT 1;

    IF fk_name IS NOT NULL THEN
        -- 동적 SQL을 사용하여 외래키 제약 조건 삭제
        SET @s = CONCAT('ALTER TABLE COMMENT DROP FOREIGN KEY ', fk_name);
        PREPARE stmt FROM @s;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

DELIMITER ;

CALL DropForeignKey();

-- 기존 댓글 테이블의 외래키 삭제
ALTER TABLE COMMENT DROP COLUMN PARENT_COMMENT_ID;
