CREATE TABLE `FEED_RESPONSE`
(
    `FEED_ID`      BIGINT,
    `WRITER_ID`    BIGINT,
    `WRITER_USERNAME`     VARCHAR(10),
    `GRAPHIC_CONTENT_PATHS` TEXT,
    `TAG_NAMES`    TEXT,
    `CREATED_AT`   DATETIME(6),
    `TEXT_CONTENT` TEXT,
    `LATITUDE`     DOUBLE,
    `LONGITUDE`    DOUBLE,
    `CITY`         VARCHAR(35),
    `COUNTRY`      VARCHAR(50),
    PRIMARY KEY (`FEED_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

INSERT INTO `FEED_RESPONSE`(FEED_ID, WRITER_ID, WRITER_USERNAME, GRAPHIC_CONTENT_PATHS, TAG_NAMES, CREATED_AT, TEXT_CONTENT, LATITUDE, LONGITUDE, CITY, COUNTRY)
SELECT F.ID,
       M.ID,
       M.USERNAME,
       JSON_ARRAYAGG(
           JSON_OBJECT(
                'id', GC.id,
                'path', GC.path
           )
       ),
       JSON_ARRAYAGG(T.TAG_NAME),
       F.CREATED_AT,
       F.TEXT_CONTENT,
       F.LATITUDE,
       F.LONGITUDE,
       F.CITY,
       F.COUNTRY
FROM FEED F
LEFT JOIN MEMBER M ON F.MEMBER_ID = M.ID
LEFT JOIN GRAPHIC_CONTENT GC on F.ID = GC.FEED_ID
LEFT JOIN FEED_TAG FT on F.ID = FT.FEED_ID
LEFT JOIN TAG T on FT.TAG_ID = T.ID
GROUP BY F.ID;