CREATE TABLE `CLICK_LOG`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `MEMBER_ID` BIGINT NOT NULL ,
    `FEED_ID` BIGINT NOT NULL ,
    `CREATED_AT` DATETIME(6) NOT NULL ,
    PRIMARY KEY (`ID`),
    INDEX `IDX_MEMBER_CREATED` (`MEMBER_ID`, `CREATED_AT`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;