CREATE TABLE `CLICK_LOG`
(
    `ID` BIGINT,
    `MEMBER_ID` BIGINT NOT NULL ,
    `FEED_ID` BIGINT NOT NULL ,
    `CREATED_AT` DATETIME(6) NOT NULL ,
    PRIMARY KEY (`ID`),
    INDEX `IDX_MEMBER_CREATED` (`MEMBER_ID`, `CREATED_AT`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `INTERESTED_TAGS`
(
    `MEMBER_ID` BIGINT,
    `TAGS` VARCHAR(255),
    PRIMARY KEY (`MEMBER_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;