CREATE TABLE `FOLLOW`
(
    `ID`                 BIGINT      NOT NULL AUTO_INCREMENT,
    `FOLLOWER_ID`        BIGINT      NOT NULL,
    `FOLLOWEE_ID`        BIGINT      NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`FOLLOWER_ID`) REFERENCES `MEMBER` (`ID`),
    FOREIGN KEY (`FOLLOWEE_ID`) REFERENCES `MEMBER` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;