CREATE TABLE `MEMBER`
(
    `ID`                 BIGINT      NOT NULL AUTO_INCREMENT,
    `EMAIL`              VARCHAR(25) NOT NULL,
    `ENCRYPTED_PASSWORD` VARCHAR(60) NOT NULL,
    `USERNAME`           VARCHAR(10) NOT NULL,
    `PROFILE_IMAGE_PATH` VARCHAR(255),
    `INTRODUCTION`       TEXT,
    `DELETED`            TINYINT(1)     NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `FEED`
(
    `ID`           BIGINT NOT NULL AUTO_INCREMENT,
    `MEMBER_ID`    BIGINT NOT NULL,
    `CREATED_AT`   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `TEXT_CONTENT` TEXT   NOT NULL,
    `LATITUDE`     DOUBLE NOT NULL,
    `LONGITUDE`    DOUBLE NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `GRAPHIC_CONTENT`
(
    `id`       BIGINT       NOT NULL AUTO_INCREMENT,
    `FEED_ID`  BIGINT       NOT NULL,
    `PATH`     VARCHAR(255) NOT NULL,
    `SEQUENCE` TINYINT(1)      NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `PATH` (`PATH`),
    FOREIGN KEY (`FEED_ID`) REFERENCES `FEED` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `COMMENT`
(
    `ID`                BIGINT       NOT NULL AUTO_INCREMENT,
    `MEMBER_ID`         BIGINT       NOT NULL,
    `FEED_ID`           BIGINT       NOT NULL,
    `PARENT_COMMENT_ID` BIGINT,
    `TEXT_CONTENT`      VARCHAR(200) NOT NULL,
    `CREATED_AT`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `DELETED`           TINYINT(1)      NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`),
    FOREIGN KEY (`FEED_ID`) REFERENCES `FEED` (`ID`),
    FOREIGN KEY (`PARENT_COMMENT_ID`) REFERENCES `COMMENT` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `TAG`
(
    `ID`       BIGINT      NOT NULL AUTO_INCREMENT,
    `TAG_NAME` VARCHAR(15) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `TAG_NAME` (`TAG_NAME`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `FEED_TAG`
(
    `FEED_ID` BIGINT NOT NULL,
    `TAG_ID`  BIGINT NOT NULL,
    PRIMARY KEY (`FEED_ID`, `TAG_ID`),
    FOREIGN KEY (`FEED_ID`) REFERENCES `FEED` (`ID`),
    FOREIGN KEY (`TAG_ID`) REFERENCES `TAG` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE TABLE `LIKES`
(
    `ID`        BIGINT NOT NULL AUTO_INCREMENT,
    `MEMBER_ID` BIGINT NOT NULL,
    `FEED_ID`   BIGINT NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `LIKES_UNIQUE_CONSTRAINTS` (`MEMBER_ID`, `FEED_ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`),
    FOREIGN KEY (`FEED_ID`) REFERENCES `FEED` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;
