CREATE TABLE `DIARY`
(
    `ID`        BIGINT      NOT NULL AUTO_INCREMENT,
    `MEMBER_ID` BIGINT      NOT NULL,
    `TITLE`     VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

ALTER TABLE `FEED`
    ADD COLUMN `DIARY_ID` BIGINT NULL,
    ADD FOREIGN KEY (`DIARY_ID`) REFERENCES `DIARY` (`ID`);