ALTER TABLE `DIARY`
    DROP COLUMN THUMBNAIL_PATH;
ALTER TABLE `DIARY`
    ADD COLUMN THUMBNAIL_ID BIGINT NOT NULL,
    ADD CONSTRAINT fk_diary_thumbnail_id FOREIGN KEY (THUMBNAIL_ID) REFERENCES GRAPHIC_CONTENT(ID);
