CREATE TABLE `CHAT_ROOM`
(
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CHAT_ROOM_MEMBER`
(
    `CHAT_ROOM_ID` BIGINT(20) NOT NULL,
    `MEMBER_ID`    BIGINT(20) NOT NULL,
    PRIMARY KEY (`CHAT_ROOM_ID`, `MEMBER_ID`),
    FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `CHAT_ROOM` (`ID`),
    FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CHAT_MESSAGE`
(
    `ID`           BIGINT(20) NOT NULL AUTO_INCREMENT,
    `SENDER_ID`    BIGINT(20) NOT NULL,
    `CHAT_ROOM_ID` BIGINT(20) NOT NULL,
    `TEXT_CONTENT` TEXT     NOT NULL,
    `CREATED_AT`   DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`SENDER_ID`) REFERENCES `MEMBER` (`ID`),
    FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `CHAT_ROOM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
